#!/bin/bash
echo ""
echo "🚀 DÉPLOIEMENT RAPIDE - Edge Function create-stripe-checkout"
echo "=============================================================="
echo ""
echo "📋 Commandes à exécuter :"
echo ""
echo "1. Installer Supabase CLI (si pas déjà fait) :"
echo "   sudo npm install -g supabase"
echo ""
echo "2. Se connecter :"
echo "   supabase login"
echo ""
echo "3. Lier le projet :"
echo "   supabase link --project-ref ewlozuwvrteopotfizcr"
echo ""
echo "4. Déployer l'Edge Function :"
echo "   supabase functions deploy create-stripe-checkout"
echo ""
echo "5. Configurer les secrets dans Dashboard :"
echo "   Settings → Edge Functions → Secrets"
echo "   - STRIPE_SECRET_KEY"
echo "   - STRIPE_WEBHOOK_SECRET"
echo ""
echo "6. Redéployer après configuration des secrets :"
echo "   supabase functions deploy create-stripe-checkout"
echo ""
echo "📖 Guide complet : DEPLOY_AUTO_EDGE_FUNCTION.md"
echo ""
